import { z } from "zod";

const clientEnvSchema = z.object({
  NEXT_PUBLIC_CONVEX_URL: z.string().min(1),
  NEXT_PUBLIC_STELLAR_NETWORK: z.enum(["testnet"]).default("testnet"),
  NEXT_PUBLIC_STELLAR_NETWORK_PASSPHRASE: z.string().min(1),
  NEXT_PUBLIC_STELLAR_RPC_URL: z.string().url(),
  NEXT_PUBLIC_GAME_HUB_CONTRACT_ID: z.string().min(1),
  NEXT_PUBLIC_CF_HUB_CONTRACT_ID: z.string().min(1).optional(),
  NEXT_PUBLIC_STELLAR_HORIZON_URL: z.string().url(),
  NEXT_PUBLIC_CF_GAME_CONTRACT_ID: z.string().min(1).optional(),
  NEXT_PUBLIC_CF_ULTRAHONK_VERIFIER_CONTRACT_ID: z.string().min(1).optional(),
});

export const envClient = clientEnvSchema.parse({
  NEXT_PUBLIC_CONVEX_URL: process.env.NEXT_PUBLIC_CONVEX_URL,
  NEXT_PUBLIC_STELLAR_NETWORK: process.env.NEXT_PUBLIC_STELLAR_NETWORK,
  NEXT_PUBLIC_STELLAR_NETWORK_PASSPHRASE:
    process.env.NEXT_PUBLIC_STELLAR_NETWORK_PASSPHRASE,
  NEXT_PUBLIC_STELLAR_RPC_URL: process.env.NEXT_PUBLIC_STELLAR_RPC_URL,
  NEXT_PUBLIC_GAME_HUB_CONTRACT_ID:
    process.env.NEXT_PUBLIC_GAME_HUB_CONTRACT_ID,
  NEXT_PUBLIC_CF_HUB_CONTRACT_ID: process.env.NEXT_PUBLIC_CF_HUB_CONTRACT_ID,
  NEXT_PUBLIC_STELLAR_HORIZON_URL: process.env.NEXT_PUBLIC_STELLAR_HORIZON_URL,
  NEXT_PUBLIC_CF_GAME_CONTRACT_ID: process.env.NEXT_PUBLIC_CF_GAME_CONTRACT_ID,
  NEXT_PUBLIC_CF_ULTRAHONK_VERIFIER_CONTRACT_ID:
    process.env.NEXT_PUBLIC_CF_ULTRAHONK_VERIFIER_CONTRACT_ID,
});
